name: e_commerce
description: e_commerce_frontend
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  email_validator: ^1.0.0
  local_auth: ^0.6.2+3
  flutter_rounded_date_picker: ^1.0.5+1
  flutter_secure_storage: ^3.3.3
  dot_navigation_bar: ^0.1.1
  auto_size_text: ^2.1.0
  material_design_icons_flutter: 4.0.5555
  barcode_scan: ^1.0.0
  flip_card: ^0.4.4
  smooth_star_rating: ^1.1.1
  qr_flutter: ^3.2.0
  pdf: ^1.11.2
  path_provider: ^1.6.22
  font_awesome_flutter: ^8.10.0
  solid_bottom_sheet: ^0.1.9
  url_launcher: ^5.7.6
  flutter_share: ^1.0.2+1
  image_picker: ^0.6.7+17
  share: ^0.6.5+4
  numberpicker: ^1.2.1
  flutter_time_picker_spinner: ^1.0.6+1
  firebase_storage: ^5.0.1
  firebase_core : ^0.5.0
  flushbar: ^1.5.0
  date_time_picker: ^1.0.2
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto-Light
      fonts:
          - asset: assets/fonts/Roboto-Light.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf